### ISSUE TITLE
how to track release date(s)

### ISSUE THREAD

**Issue by DavidOrchard** [toomuchdesign/next-page-tester#132]
Is there a way to track when releases will be tagged/made?  A slack channel perhaps? I'm very interested in v0.18.0 for the url object fix.

**Comment by toomuchdesign** [comment]
Hi @DavidOrchard, we guess we're all done for v.0.18.0. If @Meemaw agrees to release current partial not found page support, we can publish.

Having a more structured maintenance would be cool, but it's currently totally out of reach since the whole project relies on @Meemaw's (🤟) and my free time.

We're totally open to take new contributors in, no need to say.

**Comment by Meemaw** [comment]
I think we should be good to release what we currently have. Not found page implementation might take some more time and its a new feature anyway so shouldn't be a blocker.

**Comment by toomuchdesign** [comment]
V0.18.0 released 🚢
