### ISSUE TITLE
Integrating with Apollo MockedProvider

### ISSUE THREAD

**Issue by zkwsk** [toomuchdesign/next-page-tester#134]
## 💬 Questions and Help

I have an application using Apollo Client to query a GraphQL backend. Is it possible to use Apollos [MockedProvider](https://www.apollographql.com/docs/react/development-testing/testing/#the-mockedprovider-component) instead og node-mocks-http?

Can you help me how I might integrate next-page-tester with MockedProvider?

**Comment by Meemaw** [comment]
Hi @zkwsk 👋 Thanks for bringing this problem up.

Currently we do not provide a way to wrap the component tree with custom components as we are thinking in terms of full pages (like in production) and not components; thus this is not possible.

However, I can see how this could be useful when such mocked providers are needed. To solve this we could use something similar that [react-hooks-testing-library](https://react-hooks-testing-library.com/reference/api#wrapper) already uses, by adding `wrapper` option to the `getPage.

It might look something like this:

```js
const { render } = await getPage({
  route: '/',
  wrapper: (children) => <MockedProvider mocks={mocks}>{children}</MockedProvider>
})

Would such API make sense for you and solve your issues?

**Comment by zkwsk** [comment]
Having the option to specify wrappers on the 3 levels like that would be a very welcome addition. I think you're right that we need to maintain the order of the providers in the hierarchy. Do you want me to try to have a go at a PR or is it something you could implement relatively quickly?

**Comment by Meemaw** [comment]
You are more than welcome to provide a PR! Before that, I would just like to agree on the API and get @toomuchdesign's opinion on this.

Thinking some more about it, I actually think we should support wrapper at each level (`Component`, `App` and `Document`) because:
- With a single `wrapper` it is not clear where the wrapping actually happens; is it around `Document` or something else?
- It is more flexible; should support all use-cases where more granular `Providers` are needed

**Comment by toomuchdesign** [comment]
Hi! I Actually only have questions to bring in :)

What is `MockedProvider` supposed to wrap in a Next.js application? I see an [`ApolloProvider` at `_app` level](https://github.com/vercel/next.js/blob/canary/examples/api-routes-apollo-server-and-client-auth/pages/_app.js) in Next.js repo.

Do we expect Apollos `MockedProvider` to be able to work also during server side render?

I'm not sure what are the implications of providing a `Document` wrapper since `Document` does not render client side.

I understand Apollos `MockedProvider` should be defined at test declaration time, therefore it might be necessary to provide a way to wrap the rendered tree. Is there any case where it could be necessary wrapping the page and not _app component?

**Comment by Meemaw** [comment]
> I understand Apollos `MockedProvider` should be defined at test declaration time, therefore it might be necessary to provide a way to wrap the rendered tree. Is there any case where it could be necessary wrapping the page and not _app component?

If we wrap `_app` instead of `_page` and user has a custom `_app`, `MockedProvider` will never be used (its higher in the component tree). I think we need to wrap `Component` to cover this use-case. I would however still go with an object based API for flexibility, to avoid future breaking changes if we want to add support for other levels of wrapping.

```js
wrapper: {
   Component?: React.FC,
}
```

**Comment by toomuchdesign** [comment]
Hi @Meemaw, ok for the object API 👍 
I still don't get why the wrapper wouldn't be rendered in case of a custom `_app`... In my mind I pictured it like this:

```html
<OptionalCustomDocument>
  <Wrapper>
    <DefaultAppOrCustomApp>
      <Page>
```

**Comment by Meemaw** [comment]
It would be rendered but `MockedProvider` is essentially a modified `ApolloProvider` under the hood https://github.com/apollographql/apollo-client/blob/main/src/utilities/testing/mocking/MockedProvider.tsx#L61.

Because `ApolloProvider` is also defined at the app level (`DefaultAppOrCustomApp`): https://github.com/vercel/next.js/blob/canary/examples/api-routes-apollo-server-and-client-auth/pages/_app.js#L8 we would have a problem.

`useContext(ApolloProvider)` will return the `ApolloProvider` from the custom `_app` and not he mocked instance from the wrapper as user would want in tests.

**Comment by toomuchdesign** [comment]
I see. Therefore the idea is rendering both and shadowing `ApolloProvider `, right?

In this case if we rendered `MockedProvider` around the page and Apollo was also consumed by the `_app` component, wouldn't this solution fall short anyway?

Would it be make sense making the real `ApolloProvider` renderable optionally (in userland code) and the wrap `MockedProvider ` from `_app` component? 😬

**Comment by Meemaw** [comment]
> I see. Therefore the idea is rendering both and shadowing `ApolloProvider `, right?
> 
> In this case if we rendered `MockedProvider` around the page and Apollo was also consumed by the `_app` component, wouldn't this solution fall short anyway?

I don' think this is actually a case, but if someone did it they would need to wrap the `_app` with `MockedProvider` as well.

Essentially, they would need to do something like this:

```js
const { render } = await getPage({
  route: '/',
  wrapper: {
     Component: (children) => <MockedProvider mocks={mocks}>{children}</MockedProvider>,
     App: (children) => <MockedProvider mocks={mocks}>{children}</MockedProvider>
   }
})
```

> 
> Would it be make sense making the real `ApolloProvider` renderable optionally (in userland code) and the wrap `MockedProvider ` from `_app` component? 😬

I don't think user code should need to be changed/complicated to make this possible.

**Comment by toomuchdesign** [comment]
Got it, thank you @Meemaw!
Let's bake it a little bit and setup a PR after 404 cycle. 👍 

What if:
- `Component` was `Page`
- and `React.FC` -> `(children: JSX.element) => JSX.element`?

(I actually have no idea what `React.FC` does :) )

@zkwsk we can totally provide support if you wanted to give it a try and find out if this proposal fits your testing needs.

**Comment by Meemaw** [comment]
> Got it, thank you @Meemaw!
> Let's bake it a little bit and setup a PR after 404 cycle. 👍
> 
> What if:
> 
> * `Component` was `Page`

👍 

> * and `React.FC` -> `(children: JSX.element) => JSX.element`?
> 
> (I actually have no idea what `React.FC` does :) )

`React.FC` extends  `(children: JSX.element) => JSX.element` so they would overlap, but I agree that `(children: JSX.element) => JSX.element` is simpler

> 
> @zkwsk we can totally provide support if you wanted to give it a try and find out if this proposal fits your testing needs.

**Comment by Meemaw** [comment]
Hi @zkwsk 👋  I've prepared a draft PR that enables/fixes this issue. You can see example usage here: https://github.com/toomuchdesign/next-page-tester/blob/92393faac9ec19635e81c5fc66d30db5e6089fd5/examples/03-apollo-client.md

Let me know if this would work for you.
