### ISSUE TITLE
Can this work with a Apollo graphql API route?

### ISSUE THREAD

**Issue by domhede** [toomuchdesign/next-page-tester#211]
## 💬 Questions and Help

Your question.
Will this work with a Apollo graphql server running from an API route?
I'm trying to test a SSR page with a server side query called within getServerSideProps.

I am getting some unexpected errors.
Mainly 
```
Timeout - Async callback was not invoked within the 5000 ....
```

## Reproduction
https://github.com/domhede/next-page-tester-demo

Failing test:
https://github.com/domhede/next-page-tester-demo/blob/main/components/pages/profile/profile.test.tsx

**Comment by Meemaw** [comment]
Hi @domhede 👋 have you followed our [Apollo example](https://github.com/toomuchdesign/next-page-tester/blob/master/examples/03-apollo-client.md)?

(not sure if relevant): next-page-tester does not server `/api` routes in case you were waiting for those to return a response.

**Comment by domhede** [comment]
Hi @Meemaw,

Thanks, yes I think the issue is that the app relies on the api route to serve the graphql endpoint.  Do you know if there is any workaround or a plan to add support for api routes?

**Comment by Meemaw** [comment]
Adding support for api routes would be a huge feature. As it is currently not supported you'll just have to mock the requests.

**Comment by Meemaw** [comment]
@toomuchdesign what are your thoughts on supporting `/api` routes? I think this would be a next level feature. So I imagine to make it work we would need to intercept the requests to `/api` somehow and then just have our logic (similar to how we load pages) to load the API handler, execute it and return the response.

**Comment by toomuchdesign** [comment]
As fas as I know, the only case where we need to make `/api` routes available is when they are contacted by a client application (in our case the application itself running in-browser contacting its own `/api` endpoint).

Any other internal BE to BE request involving `/api` should be performed by importing and executing the relevant code instead of contacting `/api` through the network layer (I remember Next.js docs mentioning this).

Am I missing something?

BTW, I'm personally not planning to invest time on this feature. Curious to hear your thoughts, though.

**Comment by domhede** [comment]
Hi there,
