### ISSUE TITLE
Usage with @aws-amplify next/SSR

### ISSUE THREAD

**Issue by arelaxend** [toomuchdesign/next-page-tester#64]
Hi there,

## 🚀 Feature Proposal
While using `withSSRContext` from @aws-amplify (https://github.com/aws-amplify/amplify-js) in `getServerSideProps` we get
`ReferenceError: window is not defined`

Should we mock `getServerSideProps` ?

**Comment by Meemaw** [comment]
Hey @arelaxend . `getServerSideProps` is executed on server where `window` is not defined. Does this work for you in Next.JS?

**Comment by arelaxend** [comment]
Sure it does

**Comment by Meemaw** [comment]
Can you tell me which version of `next-page-tester` you are using? After that I can look into what is happening.

**Comment by Meemaw** [comment]
I looked into this and its caused by a very annoying issue we are facing in this library: external modules evaluating `document` | `window` existence on top level (on import).

@toomuchdesign `@aws-amplify` first checks if its browser environment upon import and that evaluates to `true` because of JSDOM, and then tries to access `localStorage` in `getServerSideProps`.

I expect this will cause problems with many external libraries and we probably need a good solution for this.

**Comment by toomuchdesign** [comment]
Hi @Meemaw!
I confirm that `require.cache` (and therefore any library relying on his) is not an option with `jest`.

If we could split our initial rendering process in 2 consecutive phases (server, browser) we might consider:
- temporarily remove browser global objects (on tests setup)
- execute server logic
- restore browser global objects
- resetting modules

The last step would be framework-specific. We might consider:
- detecting Jest (`typeof jest !== 'undefined'` 😄 )
- clearing modules via `jest.resetModules()`
- clearing modules via `require.cache` in case no known test frameworks are detected
- optionally provide a module clearing callback configurable by users

I suspect this would still leave room for bugs, though.

[This](https://github.com/toomuchdesign/next-page-tester/blob/master/src/getPage.tsx#L118) could be a good line to reset modules and browser global objects.

Another option could involve using Jest in `node` environment, and initialise JSDOM on our side before we return page element.

How about adding some failing tests [here](https://github.com/toomuchdesign/next-page-tester/tree/master/src/__tests__/global-object) so that we can reproduce the problem and experiment solutions?

**Comment by toomuchdesign** [comment]
A fix is available in #73 which is blocked until Jest v27 gets released.
