### ISSUE TITLE
It should be possible to only set pages directory once

### ISSUE THREAD

**Issue by jasonwilliams** [toomuchdesign/next-page-tester#9]
I’m liking the look of this library, it seems exactly what I’m after.

I wonder if the page directory can be set somewhere once, as this won’t change from test to test. There’s a lot of repetition there. Can there be some config to set the location once and not again in future tests. Maybe in package.json.

Now that I think about it, you could keep traversing up until you hit a pages directory as you’re guaranteed to have one. So most users would never need to set this at all.

**Comment by toomuchdesign** [comment]
Hi @jasonwilliams,
yep, `pagesDirectory` currently produces quite a lot of repetition. I considered a few solutions and decided to focus and the business logic and introduce such optimizations if/when the project gains more traction.

You might temporarily consider using a wrapper function which provides `getPage` with any sensible option. Something like:

```js
import { getPage as originalGetPage } from 'next-page-tester';

const pagesDirectory = process.cwd() + 'your/path/to/pages';
export async getPage function(...args){
  return originalGetPage({
    pagesDirectory,
    ...args,
  })
}
```
How do you like it?

Greetings!

**Comment by jasonwilliams** [comment]
It would be nice to not have to write that at all, but thanks for the solution.

> I considered a few solutions and decided to focus and the business logic and introduce such optimizations if/when the project gains more traction.

What were your solutions? Was there a reason they didn’t make it? I can understand it may be tricky to implement. 
I don’t consider this an optimisation, I would expect a “Next.js page tester” to know where my pages are. It seems like a lot of boilerplate to write just to have it work. That’s just my opinion though, everything else looks great 👍

**Comment by toomuchdesign** [comment]
Thanks for your feedback.

As you mentioned, I considered both automagically finding `pages` folder aligning to [Next.js specs](https://nextjs.org/docs/advanced-features/src-directory) or somehow providing a higher level configuration setup. The first option sounds the more appropriate to me.

`pageExtensions` option suffers also of the same explicitness issue, since its value could be derived from `next.config.js` file.

The only reason why I didn't introduce this logic was to not bloat the first release. BTW I believe they are both valid improvements.

I'm considering publishing a new major to align the utility with Next.js v10 and It could be the right opportunity for such improvements. ✌️

**Comment by jasonwilliams** [comment]
Thanks for your response. That makes sense..

> I'm considering publishing a new major to align the utility with Next.js v10 and It could be the right opportunity for such improvements.

This sounds great ill look forward!

**Comment by toomuchdesign** [comment]
Just published an update (v.0.5.0) with autodetected `pagesDirectory` and `pageExtensions`.

Thanks @jasonwilliams!
Let me know if you have further feedback.

Cheers
